#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
~/.config/polybar/launch.sh &
#---------------------------------------------
#bspc monitor -d I II III IV V VI VII VIII IX X

#bspc monitor eDP1 -d 󰈹   󰕼 󰙯 󰉋
#bspc monitor eDP1 -d VI VII VIII IX X
#bspc monitor HDMI1 -d I II III IV V 

bspc config top_padding 0
#bspc config bottom_padding 0

# 󰈹   󰉓 󰿪    
#bspc monitor eDP1 -d 󰼏 󰼐 󰼑 󰼒 󰼓
bspc monitor eDP1 -d 󰎳 󰎶 󰎹 󰎼 󰽽 
bspc monitor HDMI1 -d 󰎤 󰎧 󰎪 󰎭 󰎱

bspc config automatic_scheme alternate
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
#----------------------------------------------
~/scripts/launch_polybar.sh &
#####################################################
bspc rule -a firefox:Toolkit state=floating
bspc rule -a brave:Toolkit state=floating
#bspc rule -a firefox:Navigator state=floating
bspc rule -a Tk state=floating
# bspc rule -a "ticktick" state=floating sticky=on center=on follow=on
####################
bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle true
bspc config single_monocle false

bspc config active_border_color "#9370DB"
bspc config focused_border_color "#d8a657"
bspc config normal_border_color "#9ece6a"
######################################################

