#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
~/.config/polybar/launch.sh &
#---------------------------------------------
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor HDMI1 -d VI VII VIII IX X
bspc monitor eDP1 -d I II III IV V 

bspc config automatic_scheme alternate
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
#----------------------------------------------
~/scripts/launch_polybar.sh &
xautolock -time 10 -locker slock&
redshift-gtk &
caffeine-indicator &
caffeine &
picom &
diodon &
#polybar &
#variety &
spotify &
discord &
nm-applet &
xinput set-prop 13 "libinput Tapping Enabled" 1
#nitrogen --restore
#xrandr --output HDMI-1 --auto --right-of eDP-1
xwallpaper --maximize /mnt/Storage/Media/Imgs\ \&\ Vids/Imgs/Wallpapers/stars_squared.png
blueman-manager &
#####################################################

setxkbmap -layout "us,ar" -option "grp:alt_shift_toggle"
bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle true
bspc config single_monocle false

bspc config active_border_color "#9370DB"
bspc config focused_border_color "#9370DB"
bspc config normal_border_color "#373b41"
######################################################

