#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
~/.config/polybar/launch.sh &
#---------------------------------------------
bspc monitor -d I II III IV V VI VII VIII IX

bspc monitor HDMI-1 -d VI VII VIII IX
bspc monitor eDP-1 -d I II III IV V

bspc config automatic_scheme alternate
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
#----------------------------------------------
kdeconnect-indicator &
caffeine-indicator &
caffeine &
picom &
diodon &
polybar &
variety &
nm-applet &
redshift -P -m randr -l 30:31.2 -t 6500:5000 &
xinput set-prop 13 "libinput Tapping Enabled" 1
xrandr --output HDMI-1 --auto --right-of eDP-1
blueman-manager &
#####################################################

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle true
bspc config single_monocle false

bspc config active_border_color "#e83a3f"
bspc config focused_border_color "#b03648"
bspc config normal_border_color "#373b41"
######################################################

