splash = false
ipc = true

wallpaper {
    monitor = eDP-1
    path = /home/bahaa/.local/share/waypaper-engine/images/wallhaven-8b2c4a1b-c206-41c8-b729-8b04fa7d8966.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/bahaa/.local/share/waypaper-engine/images/wallhaven-8b2c4a1b-c206-41c8-b729-8b04fa7d8966.jpg
    fit_mode = cover
}

