splash = false
ipc = true

wallpaper {
    monitor = eDP-1
    path = /home/bahaa/.local/share/waypaper-engine/images/wallhaven-a4dca0ab-14ff-49b7-b0af-9e4d0c8988ed.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/bahaa/.local/share/waypaper-engine/images/wallhaven-a4dca0ab-14ff-49b7-b0af-9e4d0c8988ed.jpg
    fit_mode = cover
}

