preload = /home/bahaa/Pictures/Downloaded/wallhaven_wallhaven_cc_search_q_id_3A2321_sorting_random_ref_fp_seed_jUhl2b_page_6/night_city.png

wallpaper {
    monitor = eDP-1
    path = /home/bahaa/Pictures/Downloaded/wallhaven_wallhaven_cc_search_q_id_3A2321_sorting_random_ref_fp_seed_jUhl2b_page_6/night_city.png
}

wallpaper {
    monitor = DP-1
    path = /home/bahaa/Pictures/Downloaded/wallhaven_wallhaven_cc_search_q_id_3A2321_sorting_random_ref_fp_seed_jUhl2b_page_6/night_city.png
}

splash = false
