source = $HOME/.config/hypr/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

# BACKGROUND
background {
    monitor =
    path = ~/Pictures/Downloaded/wallhaven_wallhaven_cc_search_q_id_3A2321_sorting_random_ref_fp_seed_jUhl2b_page_6/blasp.png
    blur_passes = 2
    blur_size = 6
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    color = $base
}

# WEATHER
label {
    monitor =
    text = cmd[update:600000] ~/.config/hypr/scripts/weather.sh
    color = $text
    font_size = 14
    font_family = $font
    position = 40, -40
    halign = left
    valign = top
}

# NEXT PRAYER
label {
    monitor =
    text = cmd[update:30000] ~/.config/hypr/scripts/prayer.sh
    color = $text
    font_size = 13
    font_family = $font
    position = 40, -100
    halign = left
    valign = top
}

# TIME
label {
    monitor =
    text = $TIME
    color = $text
    font_size = 90
    font_family = $font
    position = -40, -40
    halign = right
    valign = top
}

# DATE 
label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $text
    font_size = 25
    font_family = $font
    position = -40, -190
    halign = right
    valign = top
}

# GREETING
label {
    monitor =
    text = cmd[update:60000] echo "Good $(date +%H | awk '{if ($1 < 12) print "morning"; else if ($1 < 18) print "afternoon"; else print "evening"}'), $USER"
    color = $subtext0
    font_size = 18
    font_family = $font
    position = 0, 45
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = $surface0
    font_color = $text
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
    hide_input = false
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, -35
    halign = center
    valign = center
}

# KEYBOARD LAYOUT
label {
    monitor =
    text = $LAYOUT
    color = rgba(205, 214, 244, 0.8)
    font_size = 14
    font_family = $font
    position = 30, 25
    halign = left
    valign = bottom
}

# MEDIA PLAYER - TRACK INFO & PROGRESS
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/media.sh info
    color = $text
    font_size = 12
    font_family = $font
    position = 0, 65
    halign = center
    valign = bottom
    text_align = center
}

# MEDIA PLAYER - PREVIOUS
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/media.sh prev
    color = $accent
    font_size = 18
    font_family = $font
    position = -45, 25
    halign = center
    valign = bottom
    onclick = playerctl previous
}

# MEDIA PLAYER - PLAY / PAUSE
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/media.sh play
    color = $accent
    font_size = 20
    font_family = $font
    position = 0, 25
    halign = center
    valign = bottom
    onclick = playerctl play-pause
}

# MEDIA PLAYER - NEXT
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/media.sh next
    color = $accent
    font_size = 18
    font_family = $font
    position = 45, 25
    halign = center
    valign = bottom
    onclick = playerctl next
}

# BATTERY
label {
    monitor =
    text = cmd[update:5000] ~/.config/hypr/scripts/battery.sh
    color = rgba(205, 214, 244, 0.8)
    font_size = 14
    font_family = $font
    position = -30, 25
    halign = right
    valign = bottom
}
