################
### MONITORS ###
################

# monitor=DP-2,preferred,-1280x0,auto
# monitor=eDP-1,1920x1080@60Hz,auto,1

# Main laptop display at origin (0x0)
monitor = eDP-1, preferred, 0x0, 1

# External monitor positioned automatically to the LEFT of eDP-1
monitor = DP-2, preferred, auto-left, 1

# Fallback for any other plugged screen
monitor = , preferred, auto-right, 1
